trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'
 
steps:
- task: Docker@2
  displayName: Build an Item Worker Image
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'hantse/wgm-item-worker'
    command: 'buildAndPush'
    Dockerfile: 'src/Worker/Dockerfile'
    buildContext: '.'
    tags: |
      $(tag)
      latest