trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'
 
steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 5.0.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions
  
  - task: DotNetCoreCLI@2
    displayName: Build project
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: "DotNet pack"
    inputs:
      command: 'pack'
      packagesToPack: '**/Item.Grpc.csproj'
      includesymbols: true
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '0'
      configuration: 'Release'

  - task: Docker@2
    displayName: Build an Character Service Image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'hantse/wgm-item-worker'
      command: 'buildAndPush'
      Dockerfile: 'src/Worker/Dockerfile'
      buildContext: '.'
      tags: |
        $(tag)
        latest