trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'
 
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git submodule update --init --recursive'
- task: Docker@2
  displayName: Build an Character Service Image
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'hantse/wgm-item-worker'
    command: 'buildAndPush'
    Dockerfile: 'src/Worker/Dockerfile'
    buildContext: '.'
    tags: |
      $(tag)
      latest