apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bank-service
  name: bank-service
  namespace: services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: bank-service
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bank-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-bank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bank-service
            port:
              number: 80