CREATE TABLE [ItemNotFound]
(
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    [ItemId] INT NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    DeleteAt DATETIME NULL,
    UpdateAt DATETIME NULL
);