CREATE TABLE [Spell]
(
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    [SpellId] INT NOT NULL,
	[NameFrFr] NVARCHAR(MAX) NOT NULL,
	[NameEnUs] NVARCHAR(MAX) NOT NULL,
	[NameEnGb] NVARCHAR(MAX) NOT NULL,
	[DescriptionFrFr] NVARCHAR(MAX) NOT NULL,
	[DescriptionEnUs] NVARCHAR(MAX) NOT NULL,
	[DescriptionEnGb] NVARCHAR(MAX) NOT NULL,
    [Value] NVARCHAR(MAX) NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateBy NVARCHAR(48) NOT NULL,
    DeleteAt DATETIME NULL,
    DeleteBy NVARCHAR(48) NULL,
    UpdateAt DATETIME NULL,
    UpdateBy NVARCHAR(48) NULL,
);